classOrder = ["SDK", "Scope"]

[docusaurus]
tagline = "Sentry SDK implementation for Roblox"

[[navbar.items]]
href = "https://discord.gg/roblox-api-332692436478590986"
label = "Discord"
position = "right"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Reliable"
description = "The SDK was designed with Roblox developers in mind. Whether you're using it for plugins or to track a game, features were tested with real Roblox environments."

[[home.features]]
title = "Flexible"
description = "Supports automatic tracking, stacktraces and desynchronized actor calls."

[[home.features]]
title = "Familiar"
description = "Follows the Sentry Unified SDK API Guidelines."