# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.7.1"
pesde = "pesde-pkg/pesde@0.7.3+registry.0.2.3"
wally = "UpliftGames/wally@0.3.2"
lune = "lune-org/lune@0.10.5"
luau-lsp = "JohnnyMorganz/luau-lsp@1.70.1"
selene = "Kampfkarren/selene@0.32.0"
stylua = "JohnnyMorganz/StyLua@2.5.2"
