[package]
name = "devsparkle/sentry-roblox"
description = "An unofficial Roblox SDK for Sentry.io"
version = "1.1.0"
license = "BSD-2-Clause"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
