name: Validate Documentation

on: [push, workflow_dispatch, workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Build steps
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build
        run: npx moonwave build --code ./