name: Build and Publish Binaries
run-name: Release binaries for ${{ github.ref_name }} by @${{ github.actor }}

on:
  release:
    types: [created]

permissions:
  contents: write

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Build steps
      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: rojo build -o SentrySDK.rbxm
      
      # Upload steps
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: SentrySDK.rbxm
